### ISSUE TITLE
Ошибка обновления с официального заббикса

### ISSUE THREAD

**Issue by das-ich** [CHERTS/zabbix_44x_next#1]
dnf update zabbix*                                                                                                                                                    
Последняя проверка окончания срока действия метаданных: 0:00:11 назад, Ср 12 мая 2021 15:27:23.
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210101-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210102-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210103-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210104-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210105-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210106-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210107-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210108-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210110-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210111-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210112-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210113-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210114-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210115-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210116-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210117-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210118-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210119-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210120-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210121-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210122-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210123-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210124-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210125-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210126-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210127-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210128-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210129-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210130-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210131-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210201-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210202-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210203-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210204-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210205-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210206-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210207-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210208-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210209-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210210-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210211-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210212-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210213-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210214-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210215-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210216-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210217-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210218-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210219-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210220-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210221-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210222-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210223-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210225-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210226-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210227-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210228-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210301-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210302-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210303-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210304-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210305-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210306-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210307-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210308-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210309-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210310-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210311-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210312-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210313-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210314-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210315-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210316-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210317-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210318-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210319-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210320-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210321-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210322-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210323-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210324-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210325-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210326-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210327-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210328-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210329-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210330-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210331-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210401-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210402-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210403-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210404-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210405-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210406-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210407-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210408-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210409-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210410-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210411-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210412-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210413-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210414-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210415-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210416-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210417-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210418-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210419-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210420-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210421-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210422-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210423-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210424-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210425-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210426-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210427-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210428-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210429-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210430-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210501-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210502-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210503-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210504-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210505-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210506-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210507-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210508-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210509-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210510-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210511-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix_cfg_localhost_20210512-0501_db-psql-4.4.2.sql.xz
Отсутствуют совпадения для аргумента: zabbix-dump.sh
Ошибка: Отсутствуют пакеты, помеченные для обновления.

OS cat /etc/redhat-release                                                                                                                                          1 ↵  
CentOS Linux release 8.3.2011
сейчас установлен
rpm -qa|grep zabbix                                                                                                                                                   
zabbix-agent-4.4.10-1.el8.x86_64
zabbix-web-pgsql-4.4.10-1.el8.noarch
zabbix-web-4.4.10-1.el8.noarch
zabbix-server-pgsql-4.4.10-1.el8.x86_64
zabbix-nginx-conf-4.4.10-1.el8.noarch
zabbix-sender-4.4.10-1.el8.x86_64
zabbix-release-4.4-1.el8.noarch

**Comment by cherts** [comment]
Вечер добрый, а вы установили новый репо как описано [тут](https://github.com/CHERTS/zabbix_44x_next/blob/master/RHELUPDATE.md)?

Покажите вывод: yum repolist

**Comment by cherts** [comment]
Для примера вот вывод с моей CentOS 8:

```
# yum repolist
repo id                                                       repo name
appstream                                                     CentOS Linux 8 - AppStream
baseos                                                        CentOS Linux 8 - BaseOS
dbs                                                           Zabbix Team of Distributed Service Official Repository - x86_64
extras                                                        CentOS Linux 8 - Extras
mariadb-main                                                  MariaDB Server
mariadb-maxscale                                              MariaDB MaxScale
mariadb-tools                                                 MariaDB Tools
```

И вывод обновления:
```

# dnf update zabbix-*
Last metadata expiration check: 0:00:34 ago on Thu 13 May 2021 12:26:12 AM +05.
Dependencies resolved.
===========================================================================================================================================================================
 Package                                           Architecture                         Version                                    Repository                         Size
===========================================================================================================================================================================
Upgrading:
 zabbix-agent                                      x86_64                               4.4.19-1.el8                               dbs                               967 k
 zabbix-apache-conf                                noarch                               4.4.19-1.el8                               dbs                               240 k
 zabbix-server-mysql                               x86_64                               4.4.19-1.el8                               dbs                               5.1 M
 zabbix-web                                        noarch                               4.4.19-1.el8                               dbs                               3.0 M
 zabbix-web-mysql                                  noarch                               4.4.19-1.el8                               dbs                                16 k

Transaction Summary
===========================================================================================================================================================================
Upgrade  5 Packages

Total download size: 9.3 M
Is this ok [y/N]: y
Downloading Packages:
(1/5): zabbix-apache-conf-4.4.19-1.el8.noarch.rpm                                                                                          270 kB/s | 240 kB     00:00
(2/5): zabbix-agent-4.4.19-1.el8.x86_64.rpm                                                                                                807 kB/s | 967 kB     00:01
(3/5): zabbix-web-mysql-4.4.19-1.el8.noarch.rpm                                                                                             42 kB/s |  16 kB     00:00
(4/5): zabbix-server-mysql-4.4.19-1.el8.x86_64.rpm                                                                                         3.1 MB/s | 5.1 MB     00:01
(5/5): zabbix-web-4.4.19-1.el8.noarch.rpm                                                                                                  2.8 MB/s | 3.0 MB     00:01
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                      4.7 MB/s | 9.3 MB     00:01
warning: /var/cache/dnf/dbs-5a12e3b7ab66857e/packages/zabbix-agent-4.4.19-1.el8.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID 5dc68ab0: NOKEY
Zabbix Team of Distributed Service Official Repository - x86_64                                                                            3.0 MB/s | 3.1 kB     00:00
Importing GPG key 0x5DC68AB0:
 Userid     : "Zabbix Team of Distributed Service <support@db-service.ru>"
 Fingerprint: 1C03 FE2E 2FFE 1CD9 D2D9 047C A006 8CA0 5DC6 8AB0
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-dbs
Is this ok [y/N]: y
Key imported successfully
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                   1/1
  Running scriptlet: zabbix-web-4.4.19-1.el8.noarch                                                                                                                    1/1
  Upgrading        : zabbix-web-4.4.19-1.el8.noarch                                                                                                                   1/10
warning: /etc/php-fpm.d/zabbix.conf created as /etc/php-fpm.d/zabbix.conf.rpmnew

  Running scriptlet: zabbix-web-4.4.19-1.el8.noarch                                                                                                                   1/10
  Upgrading        : zabbix-apache-conf-4.4.19-1.el8.noarch                                                                                                           2/10
  Running scriptlet: zabbix-apache-conf-4.4.19-1.el8.noarch                                                                                                           2/10
  Upgrading        : zabbix-web-mysql-4.4.19-1.el8.noarch                                                                                                             3/10
  Running scriptlet: zabbix-server-mysql-4.4.19-1.el8.x86_64                                                                                                          4/10
  Upgrading        : zabbix-server-mysql-4.4.19-1.el8.x86_64                                                                                                          4/10
warning: /etc/zabbix/zabbix_server.conf created as /etc/zabbix/zabbix_server.conf.rpmnew

  Running scriptlet: zabbix-server-mysql-4.4.19-1.el8.x86_64                                                                                                          4/10
  Running scriptlet: zabbix-agent-4.4.19-1.el8.x86_64                                                                                                                 5/10
  Upgrading        : zabbix-agent-4.4.19-1.el8.x86_64                                                                                                                 5/10
  Running scriptlet: zabbix-agent-4.4.19-1.el8.x86_64                                                                                                                 5/10
  Cleanup          : zabbix-web-mysql-4.4.10-1.el8.noarch                                                                                                             6/10
  Cleanup          : zabbix-apache-conf-4.4.10-1.el8.noarch                                                                                                           7/10
  Running scriptlet: zabbix-web-4.4.10-1.el8.noarch                                                                                                                   8/10
  Cleanup          : zabbix-web-4.4.10-1.el8.noarch                                                                                                                   8/10
  Running scriptlet: zabbix-server-mysql-4.4.10-1.el8.x86_64                                                                                                          9/10
  Cleanup          : zabbix-server-mysql-4.4.10-1.el8.x86_64                                                                                                          9/10
  Running scriptlet: zabbix-server-mysql-4.4.10-1.el8.x86_64                                                                                                          9/10
  Running scriptlet: zabbix-agent-4.4.10-1.el8.x86_64                                                                                                                10/10
  Cleanup          : zabbix-agent-4.4.10-1.el8.x86_64                                                                                                                10/10
  Running scriptlet: zabbix-agent-4.4.10-1.el8.x86_64                                                                                                                10/10
  Running scriptlet: zabbix-agent-4.4.19-1.el8.x86_64                                                                                                                10/10
  Running scriptlet: zabbix-agent-4.4.10-1.el8.x86_64                                                                                                                10/10
  Verifying        : zabbix-agent-4.4.19-1.el8.x86_64                                                                                                                 1/10
  Verifying        : zabbix-agent-4.4.10-1.el8.x86_64                                                                                                                 2/10
  Verifying        : zabbix-apache-conf-4.4.19-1.el8.noarch                                                                                                           3/10
  Verifying        : zabbix-apache-conf-4.4.10-1.el8.noarch                                                                                                           4/10
  Verifying        : zabbix-server-mysql-4.4.19-1.el8.x86_64                                                                                                          5/10
  Verifying        : zabbix-server-mysql-4.4.10-1.el8.x86_64                                                                                                          6/10
  Verifying        : zabbix-web-4.4.19-1.el8.noarch                                                                                                                   7/10
  Verifying        : zabbix-web-4.4.10-1.el8.noarch                                                                                                                   8/10
  Verifying        : zabbix-web-mysql-4.4.19-1.el8.noarch                                                                                                             9/10
  Verifying        : zabbix-web-mysql-4.4.10-1.el8.noarch                                                                                                            10/10

Upgraded:
  zabbix-agent-4.4.19-1.el8.x86_64          zabbix-apache-conf-4.4.19-1.el8.noarch      zabbix-server-mysql-4.4.19-1.el8.x86_64      zabbix-web-4.4.19-1.el8.noarch
  zabbix-web-mysql-4.4.19-1.el8.noarch

Complete!

```

**Comment by cherts** [comment]
Обратите внимание на команду:

`dnf update zabbix-*`

Я поправил документацию, была потерян знак тире.

**Comment by das-ich** [comment]
yum repolist                                                                                                                                                         
идентификатор репозитория                                                   имя репозитория
appstream                                                                   CentOS Linux 8 - AppStream
baseos                                                                      CentOS Linux 8 - BaseOS
dbs                                                                         Zabbix Team of Distributed Service Official Repository - x86_64
epel                                                                        Extra Packages for Enterprise Linux 8 - x86_64
epel-modular                                                                Extra Packages for Enterprise Linux Modular 8 - x86_64
extras                                                                      CentOS Linux 8 - Extras
grafana                                                                     grafana
nginx-mainline                                                              nginx mainline repo
powertools                                                                  CentOS Linux 8 - PowerTools
zabbix-non-supported                                                        Zabbix Official Repository non-supported - x86_64

**Comment by das-ich** [comment]
после добавления тире
стало чуть лучше
dnf update zabbix-*                                                                                                                                                   
Последняя проверка окончания срока действия метаданных: 1:54:50 назад, Чт 13 мая 2021 07:43:51.
Отсутствуют совпадения для аргумента: zabbix-dump.sh
Ошибка: Отсутствуют пакеты, помеченные для обновления.

**Comment by das-ich** [comment]
сейчас отключил zabbix-non-supported
стало вот так
yum repolist                                                                                                                                                   130 ↵  
идентификатор репозитория                                                   имя репозитория
appstream                                                                   CentOS Linux 8 - AppStream
baseos                                                                      CentOS Linux 8 - BaseOS
dbs                                                                         Zabbix Team of Distributed Service Official Repository - x86_64
epel                                                                        Extra Packages for Enterprise Linux 8 - x86_64
epel-modular                                                                Extra Packages for Enterprise Linux Modular 8 - x86_64
extras                                                                      CentOS Linux 8 - Extras
grafana                                                                     grafana
nginx-mainline                                                              nginx mainline repo
powertools                                                                  CentOS Linux 8 - PowerTools

но все равно ошибка осталась

dnf update zabbix-*                                                                                                                                                   
Последняя проверка окончания срока действия метаданных: 0:00:09 назад, Чт 13 мая 2021 09:41:56.
Отсутствуют совпадения для аргумента: zabbix-dump.sh
Ошибка: Отсутствуют пакеты, помеченные для обновления.

**Comment by cherts** [comment]
Выполните

```
dnf clean all
dnf makecache
dnf update zabbix-*
```

**Comment by das-ich** [comment]
dnf update zabbix-*                                                                                                                                                   
Последняя проверка окончания срока действия метаданных: 0:02:22 назад, Чт 13 мая 2021 17:01:36.
Отсутствуют совпадения для аргумента: zabbix-dump.sh
Ошибка: Отсутствуют пакеты, помеченные для обновления.

**Comment by cherts** [comment]
А у вас dnf хоть что-то обновляет? 

Что говорит
```
dnf search zabbix-*
dnf info zabbix-get
```

**Comment by das-ich** [comment]
отключил вашу репу и вот что захотел сделать dnf
результат транзакции
Установка    3 Пакета
Обновление  28 Пакетов
Удаление     3 Пакета

Объем загрузки: 152 M
Продолжить? [д/Н]: 

так что да, обновляет

**Comment by das-ich** [comment]
подключил вашу репу и все тоже захотелось обновиться и заббикс тоже
 zabbix-agent                                       x86_64                            4.4.19-1.el8                                           dbs                                       967 k
 zabbix-nginx-conf                                  noarch                            4.4.19-1.el8                                           dbs                                       241 k
 zabbix-sender                                      x86_64                            4.4.19-1.el8                                           dbs                                       620 k
 zabbix-server-pgsql                                x86_64                            4.4.19-1.el8                                           dbs                                       5.1 M
 zabbix-web                                         noarch                            4.4.19-1.el8                                           dbs                                       3.0 M
 zabbix-web-pgsql                                   noarch                            4.4.19-1.el8                                           dbs                                        16 k
 zlib                                               x86_64                            1.2.11-16.2.el8_3                                      baseos                                    102 k
Удаление:
 kernel                                             x86_64                            4.18.0-193.28.1.el8_2                                  @BaseOS                                     0  
 kernel-core                                        x86_64                            4.18.0-193.28.1.el8_2                                  @BaseOS                                    60 M
 kernel-modules                                     x86_64                            4.18.0-193.28.1.el8_2                                  @BaseOS                                    20 M

Результат транзакции

Установка    3 Пакета
Обновление  34 Пакета
Удаление     3 Пакета

Объем загрузки: 161 M
Продолжить? [д/Н]:

**Comment by das-ich** [comment]
но вот так 
dnf update zabbix-*                                                                                                                                              1 ↵  
Последняя проверка окончания срока действия метаданных: 0:00:30 назад, Пт 14 мая 2021 10:20:53.
Отсутствуют совпадения для аргумента: zabbix-dump.sh
Ошибка: Отсутствуют пакеты, помеченные для обновления.

все равно ошибка

**Comment by das-ich** [comment]
а если экранировать *
dnf update zabbix-\*
Последняя проверка окончания срока действия метаданных: 0:02:18 назад, Пт 14 мая 2021 10:20:53.
Зависимости разрешены.

 Пакет                                                 Архитектура                              Версия                                           Репозиторий                           Размер

Обновление:
 zabbix-agent                                          x86_64                                   4.4.19-1.el8                                     dbs                                   967 k
 zabbix-nginx-conf                                     noarch                                   4.4.19-1.el8                                     dbs                                   241 k
 zabbix-sender                                         x86_64                                   4.4.19-1.el8                                     dbs                                   620 k
 zabbix-server-pgsql                                   x86_64                                   4.4.19-1.el8                                     dbs                                   5.1 M
 zabbix-web                                            noarch                                   4.4.19-1.el8                                     dbs                                   3.0 M
 zabbix-web-pgsql                                      noarch                                   4.4.19-1.el8                                     dbs                                    16 k

Результат транзакции

Обновление  6 Пакетов

Объем загрузки: 9.9 M
Продолжить? [д/Н]:

**Comment by das-ich** [comment]
видимо надо вам это учесть в инструкции

**Comment by cherts** [comment]
> видимо надо вам это учесть в инструкции

У Вас просто какая-то мистика, у меня 
`dnf update zabbix-*`
отрабатывает без проблем, я же не с потолка взял это, а прям на реальной чистой установке CentOS 8.3 установил официальный Zabbix 4.4.10, а потом добавил свой репо и обновил до 4.4.19

Какой shell и какой версии у вас используется? bash ?

Что выдает команда?

`$SHELL --version`

У меня:
```
# $SHELL --version
GNU bash, version 4.4.19(1)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

```

**Comment by das-ich** [comment]
$SHELL --version
GNU bash, версия 4.4.19(1)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
Лицензия GPLv3+: GNU GPL версии 3 или более поздней <http://gnu.org/licenses/gpl.html>

Это свободное программное обеспечение. Вы можете изменять и распространять его.
НИКАКАЯ ГАРАНТИЯ не предоставляется в пределах, допускаемых законом.

в zsh та же ошибка без слеша
$SHELL --version                                                                                                                                                 
zsh 5.5.1 (x86_64-redhat-linux-gnu)

**Comment by 21h** [comment]
> а если экранировать *
> dnf update zabbix-*

если в текущей директории есть файлы начинающиеся с zabbix-, то шелл их может подсунуть вместо передачи маски dnf как есть.
