### ISSUE TITLE
ZBX-18556 частично импортирован

### ISSUE THREAD

**Issue by LynxChaus** [CHERTS/zabbix_44x_next#2]
Для ZBX-18556 нужен фигурный импорт коммита https://github.com/zabbix/zabbix/commit/98f91202dfdff075659fb9c4f1d4854e1327ca78 [ZBXNEXT-5691] initial draft 
т.к. в коде используется $this->cell_width которого нет.

**Comment by cherts** [comment]
Отчасти Вы правы, его нет. Но думаю будет достаточно заменить $this->cell_width на $this->gridPixels

**Comment by cherts** [comment]
Fixed in https://github.com/CHERTS/zabbix_44x_next/commit/f56b3685d76abce8b5c0a1b32a3ce100fba0ee41

**Comment by cherts** [comment]
Спасибо Андрей.
