### ISSUE TITLE
ZBX-18975 частично импортирван

### ISSUE THREAD

**Issue by LynxChaus** [CHERTS/zabbix_44x_next#3]
Коммит 4b50e4313910b9ad2d8f2a0a7a7e0e72063752ec импортирован частично, отсутствует чанк меняющий вызов 
updateSymbolsRemaining() на updateCharCount()
https://github.com/zabbix/zabbix/commit/bb9b2c44d4e01974474400f3d9171b1e66a15032#diff-de002e6567147efb48d61c2d9910e44c575d566db0de15346fdeaec1d1bfe376L165-L171

**Comment by cherts** [comment]
Добрый день, все перенесено корректно, коммит https://github.com/CHERTS/zabbix_44x_next/commit/4b50e4313910b9ad2d8f2a0a7a7e0e72063752ec это исправление как раз не полностью перенесенного ZBX-18975, а основной перенос идет в комите ранее https://github.com/CHERTS/zabbix_44x_next/commit/a4b8fe6ceb6b7e436e9f4b3423297ea4cc0ff634
